config/routes.rb
MeuProjeto::Application.routes.draw do

    devise_for :users

    get "relationships/create"

    get "relationships/destroy"

    resources :users do
        member do
            get :following, :followers
        end
    end
    resources :sessions, :only => [:create, :destroy]
    resources :relationships, :only => [:create, :destroy]
    resources :ofertas do
        resources :comments
    end

    match '/novocadastro',         :to => 'users#novocadastro'
    match '/novaoferta',           :to => 'ofertas#novaoferta'
    match '/signout',              :to => 'sessions#destroy'
    match '/ofertas_do_dia',       :to => 'ofertas#ofertas_do_dia'
    match '/ofertas_do_dia/:tipo', :to => 'ofertas#ofertas_do_dia'
    match '/home/:tipo',           :to => 'pages#home'
    match '/todas_ofertas',        :to => 'ofertas#todas_ofertas'
    match '/todas_ofertas/:tipo',  :to => 'ofertas#todas_ofertas'
  

    root :to => "pages#home"

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
        !!!TEXTO DO RODAPÉ AQUI!!!
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <nav class="round">
        <ul>
            <% if user_signed_in? %>
                <li><%= current_user.email %></li>
                <li><%= link_to "Configurações", edit_user_path(current_user) %></li>
                <li><%= link_to "Sair", signout_path, :method => :delete %></li>
            <% end %>
        </ul>
    </nav>

app/views/layouts/_menu.html.erb
    <nav class="round">
        <ul>
            <li><%= link_to "Página inicial", root_path %></li>
            <% if not user_signed_in? %>
                <li><%= form_for(:session, :url => sessions_path) do |f| %>
                    <li class="field"> <%= f.label :email %>  <%= f.text_field :email %></li>
                    <li class="field"> <%= f.label "Senha" %> <%= f.password_field :password %></li>
                    <li class="actions"> <%= f.submit "Login" %> </li>
                <% end %></li>
            <% end %>
            <% if user_signed_in? %>
                <li><%= link_to "Perfil", current_user %></li>
                <li><%= link_to "Cadastrar Oferta",  novaoferta_path %></li>
                <li><%= link_to "Ofertas do dia!", ofertas_do_dia_path %></li>
                <li><%= link_to "Todas as Ofertas", todas_ofertas_path %></li>
                <li><%= link_to "Usuários", users_path %></li>
            <% end %>
        </ul>
    </nav>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>       
        <title><%= title %></title>
        <%= csrf_meta_tag %>
        <%= render 'layouts/stylesheets' %>
        <% javascript_include_tag :defaults %>
        <%= javascript_include_tag 'jquery', 'jquery.maskMoney' %>
    </head>
    <body>
        <div class="container">
            <% if user_signed_in? %>
                <%= render 'layouts/header' %><br/><br/> 
            <% end %>
            <%= link_to logo, root_path %>
            <%= render 'layouts/menu' %>
            <section class="round">
                <% flash.each do |key, value| %>
                    <%= content_tag(:div, value, :class => "flash #{key}") %>
                <% end %>
                <% if user_signed_in? %>
                    <%= link_to "Viu uma nova Oferta? Compartilhe ela clicando aqui", novaoferta_path %><br/>
                <% end %>
                <%= yield %>
            </section>
            <%= render 'layouts/footer' %>
           <%= debug(params) if Rails.env.development? %>
        </div>

    <script type="text/javascript">
        // USER VOICE //
        var uservoiceOptions = {
            /* required */
            key: 'dealwitme',
            host: 'dealwitme.uservoice.com',
            forum: '104035',
            showTab: true,
            /* optional */
            alignment: 'right',
            background_color:'#f00',
            text_color: 'white',
            hover_color: '#06C',
            lang: 'pt_BR'
      };

      function _loadUserVoice() {
        var s = document.createElement('script');
        s.setAttribute('type', 'text/javascript');
        s.setAttribute('src', ("https:" == document.location.protocol ? "https://" : "http://") + "cdn.uservoice.com/javascripts/widgets/tab.js");
        document.getElementsByTagName('head')[0].appendChild(s);
      }
      _loadSuper = window.onload;
      window.onload = (typeof window.onload != 'function') ? _loadUserVoice : function() { _loadSuper(); _loadUserVoice(); };

    </script>

<!-- AddThis Button BEGIN -->
<script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4d6a765274c13c42"></script>
<!-- AddThis Button END -->
    </body>
</html>